server: 
  port: 9528
 
spring: 
  application:
    name: xbn-zuul-gateway


 
eureka:
  client: #客户端注册进eureka服务列表内,在多个eureka中都进行服务注册
    service-url:
      # defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka10010.com:10010/eureka/,http://eureka10011.com:10011/eureka/
      #,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: xbn-zuul-9528   #自定义微服务服务器名称
    prefer-ip-address: true     #访问路径可以显示IP地址

 #zuul和fegin的区别是，zuul是作为所有外部访问的入口
 #提供网关过滤等路由功能，fegin是微服务内部调用的一个微服务，一个对外一个对内
zuul:
  #ignored-services: mirror-provider-user  #忽略真实的微服务应用名访问
  prefix: /zuul          #定义访问前缀
  ignored-services: "*" #所有微服务的真实名字忽略
  routes:
    #mirror-provider-user.path: /users/**   #把这个微服务应用名称映射为path
    xbn-company: /company/**   #把这个微服务应用名称映射为path
    xbn-bk: /xbn/**
    store-test-product: /store/**   #购买链路微服务调用测试
  servlet-path: /        #防止前缀裁剪微服务访问地址


info:
  app.name: xbn7
  company.name: sig

  #如果Zuul使用了Ribbon做负载均衡，那么对于超大的文件（例如500M），需要提高超时设置
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000

management:
  security:
    enabled: false

env:
  test3
