server: 
  port: 9529
 
spring: 
  application:
    name: xbn-bus-application

info:
  app.name: xbn7
  company.name: sig

  #如果Zuul使用了Ribbon做负载均衡，那么对于超大的文件（例如500M），需要提高超时设置
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000

management:
  security:
    enabled: false

env:
  test3
zuul:
  #ignored-services: mirror-provider-user  #忽略真实的微服务应用名访问
  prefix: /zuul          #定义访问前缀
  ignored-services: "*" #所有微服务的真实名字忽略
  routes:
    #mirror-provider-user.path: /users/**   #把这个微服务应用名称映射为path
    xbn-company: /company/**   #把这个微服务应用名称映射为path
    xbn-bk: /xbn/**
    store-test-product: /store/**   #购买链路微服务调用测试
    xbn-bus-application: /self/**
  servlet-path: /        #防止前缀裁剪微服务访问地址
