spring:
  profiles:
    active:
    - dev
---
server:
  port: 8201
spring:
  profiles: dev
  application:
    name: mirror-config-client222
eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
  instance:
    instance-id: mirror-config-client3355  
    prefer-ip-address: true     #访问路径可以显示IP地址
---
server:
  port: 8202
spring:
  profiles: test
  application:
    name: mirror-config-client222
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
  instance:
    instance-id: mirror-config-client3355 
    prefer-ip-address: true     #访问路径可以显示IP地址

env:
  test3
